language: php
dist: trusty
sudo: false

# Supported PHP versions to test with.
php:
  - 7.2
  - 7.3
#  - 7.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  global:
    - BASE_URL="http://127.0.0.1:8080"
    - DB_URL=mysql://root@127.0.0.1/drupal
    - WEBROOT=$TRAVIS_BUILD_DIR/public

cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

before_install:

  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Disable Xdebug.
  - phpenv config-rm xdebug.ini

  # Ensure the PHP environment is ready.
  - phpenv rehash

install:

  # MySQL might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  # Create database.
  - mysql -e 'create database drupal;'

  # Do Composer install.
  #- composer install --no-interaction
  - make build

script:

  # Install Drupal.
  - vendor/bin/drush --root $WEBROOT site-install --verbose --yes --db-url="$DB_URL" minimal || travis_terminate 1;

  # Start a web server.
  - vendor/bin/drush --root $WEBROOT runserver $BASE_URL &

  # Wait until Drupal responds.
  - until curl -s $BASE_URL; do true; done > /dev/null

  # Check Drush status.
  - vendor/bin/drush --root $WEBROOT status

  # Install a module to check functionality.
  - composer require drupal/system_status --no-scripts
  - vendor/bin/drush --root $WEBROOT en --yes system_status

  # Run lints & tests.
  - make debug
  - make test-phpunit
  - make lint-php

  # Tear down
  - make clean
