language: php

php:
  - 7.1

addons:
  apt:
    packages:
      - docker-ce

cache:
  apt: true
#  directories:
#  - "$HOME/.composer/cache"

services:
  - docker

before_install:
  - rvm install 2.4
  - composer self-update

install:
#  - gem install pygmy
#  - pygmy up

script:
  - composer create-project druidfi/spell:dev-${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} mysite --no-interaction
#  - composer fix
#  - composer test-unit
#  - cd mysite
#  - make init
