language: ruby

rvm:
  - 2.4

php:
  - 7.1

addons:
  apt:
    packages:
      - docker-ce

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"

services:
  - docker

before_install:
  - echo "memory_limit = 2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -v
  - composer self-update
  - composer validate --no-check-all --ansi

install:
  - gem install pygmy
  - pygmy up

script:
  - composer create-project druidfi/spell:dev-$TRAVIS_BRANCH mysite --no-interaction
  - cd mysite
  - composer build-dev
