language: php

php:
  - 7.1
  - 7.2
  - 7.3

addons:
  apt:
    packages:
      - docker-ce

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"

services:
  - docker

before_install:
#  - rvm install 2.4

install:
#  - gem install pygmy
#  - pygmy up

script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer create-project druidfi/spell:dev-${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} mysite --no-interaction
#  - cd mysite
#  - make new
