language: ruby

rvm:
  - 2.4

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker


install:
  - gem install pygmy
  - pygmy up

before_script:
  # UID 1000 is user "drupal" inside the container.
  - sudo chown 1000:1000 -R $TRAVIS_BUILD_DIR

script:
  - composer create-project druidfi/spell:dev-$TRAVIS_BRANCH mysite --no-interaction
  - cd mysite
  - composer build-dev
