language: php

php:
  - 7.1

addons:
  apt:
    packages:
      - docker-ce

cache:
  apt: true
#  directories:
#  - "$HOME/.composer/cache"

services:
  - docker

before_install:
  - rvm install 2.4
  - composer self-update

install:
  - gem install pygmy
  - pygmy up

script:
  - composer create-project druidfi/spell:dev-${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} mysite --no-interaction
  - cd mysite
  # UID 1000 is user "drupal" inside the container.
  #- sudo chown 1000:1000 -R $TRAVIS_BUILD_DIR
  - make build-dev
