language: ruby

env:
  - PHP_VERSION="7.1"

rvm:
  - 2.4

addons:
  apt:
    packages:
      - docker-ce

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"

services:
  - docker

before_install:
  - php install $PHP_VERSION
  - composer self-update

install:
  - gem install pygmy
  - pygmy up

script:
  - composer create-project druidfi/spell:dev-$TRAVIS_BRANCH mysite --no-interaction
  - cd mysite
  - composer build-dev
