version: '3.7'

services:

  app:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-drupal"
    image: "${DRUPAL_IMAGE}"
    volumes:
      - .:/app:delegated
      - ssh:/tmp/amazeeio_ssh-agent:ro
    environment:
      APP_ENV: "${APP_ENV}"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}" # Site URI for Drush 9
      #XDEBUG_ENABLE: "true"
    networks:
      - internal
      - dev-network
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:${DRUPAL_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https

  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: druidfi/db:mysql5.7-drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal

networks:
  internal:
    external: false
  dev-network:
    name: stonehenge-network
    external: true

volumes:
  db_data:
  ssh:
    name: stonehenge-ssh
    external: true
