version: '3.7'

services:

#  frontend:
#    container_name: "${COMPOSE_PROJECT_NAME}-frontend"
#    build:
#      context: ./frontend
#      args:
#        NODE_VERSION: ${NODE_VERSION:-16}
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.entrypoints=https"
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.rule=Host(`frontend-${DRUPAL_HOSTNAME}`)"
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.tls=true"
#      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-frontend.loadbalancer.server.port=3000"
#      - "traefik.docker.network=stonehenge-network"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#      - "${DRUPAL_HOSTNAME}:host-gateway"
#    networks:
#      - internal
#      - stonehenge-network
#    depends_on:
#      - app

  app:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: "druidfi/drupal-web:php-${PHP_VERSION}"
    volumes:
      - .:/app:delegated
      - ssh:/tmp/druid_ssh-agent:ro
    environment:
      APP_ENV: "${APP_ENV:-dev}"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -S stonehenge-mailhog:1025"
      # Run `export XDEBUG_ENABLE=true` to enable xdebug.
      XDEBUG_ENABLE: "${XDEBUG_ENABLE:-false}"
      SIMPLETEST_BASE_URL: "http://app:8080"
      SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - stonehenge-network
    depends_on:
      - db

  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: druidfi/mariadb:10.5-drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - internal

networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  db_data:
  ssh:
    name: stonehenge-ssh
    external: true
