name: Create Project

on:
  pull_request:
    branches:
      - main
      - core
      - cms
  push:
    branches:
      - main
      - core
      - cms
  workflow_dispatch:

jobs:

  create-project:

    permissions:
      contents: read

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        variant: [core, cms]

    steps:

      - name: Create Docker network
        run: docker network create stonehenge-network

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Create project (${{ matrix.variant }})
        run: composer -n create-project druidfi/spell:dev-${{ matrix.variant }} my-drupal-site

      - name: Fix sites/default permissions
        run: chmod 777 my-drupal-site/public/sites/default

      - name: Create compose.override.yaml
        run: |
          cat > my-drupal-site/compose.override.yaml << 'EOF'
          services:
            app:
              ports:
                - "8080:8080"
              environment:
                DRUPAL_ROUTES: http://localhost:8080
          EOF

      - name: Print Docker Compose config
        working-directory: my-drupal-site
        run: make config

      - name: Install Drupal
        working-directory: my-drupal-site
        run: make new

      - name: Test Drupal site is accessible
        run: curl -sfI http://localhost:8080
